### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by trueauracoral** [ethanv2/podbit#10]
I am a noob. Could you please provide an example newsboat config with podbit being used?

Thank you.

**Comment by trueauracoral** [comment]
Nevermind, I found a tutorial video: https://www.youtube.com/watch?v=PyKvJ_mOsDE

**Comment by ejv2** [comment]
If you have any other trouble, re-open this issue and I'll help you out.

Also, check out the wiki: https://github.com/ejv2/podbit/wiki
